In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime
import os

In [2]:
import random

In [6]:
shippings_df = pd.read_csv('../data/csv/shipments.csv')
orders_df = pd.read_csv('../data/csv/orders_v1.csv')
transactions_df = pd.read_csv('../data/csv/transactions.csv')
inventory_logs_df = pd.read_csv('../data/csv/inventory_log_data.csv')
a

In [5]:
# Add orderIDs which have status delivered to shippings_df
shippings_df = shippings_df.merge(orders_df[orders_df['Status'] == 'Delivered'][['OrderID']], on='OrderID', how='left')
orders_shipments = orders_df.merge(shippings_df, on='OrderID', how='left')

# orderid_dates = orders_df.set_index('OrderID')['OrderDate'].to_dict() # Create a dictionary of orderid and orderdate

shippings_df['OrderDate'] = shippings_df['OrderID'].map(orderid_dates) # Map the orderid and orderdate to the shippings_df

orderid_status = dict(zip(orders_df['OrderID'],orders_df['Status'])) # Create a dictionary of orderid and status
shippings_df['Status'] = shippings_df['OrderID'].map(orderid_status)

shippings_df['DeliveryDate'] = np.nan


def shipments_adjustments(shipments_data):
    data = shipments_data
    def shipment_date_adjust(data):
        
        # When the status is cancelled, shipped date is NaN
        if shippings_df['Status'] == 'Cancelled':
            shippings_df['ShippedDate'] = np.nan
        
        # When the status is processing, shipped date is NaN
        elif shippings_df['Status'] == 'Processing':
            shippings_df['ShippedDate'] = np.nan
        
        # For all other statuses, shipped date is 1 day after or same date as the order_date
        else:   
            shippings_df['ShippedDate'] = shippings_df['OrderDate'] + datetime.timedelta(days=random.choice([0, 1]))
        
        return shippings_df

    def delivery_date_adjust(data):
        
        # Only add DeliveryDate if the status is Delivered
        if shippings_df['Status'] == 'Delivered':
            shippings_df['DeliveryDate'] = shippings_df['ShippedDate'] + datetime.timedelta(days=random.choice(range(1, 12)))
        else :
            shippings_df['DeliveryDate'] = np.nan   
            
        return shippings_df

shipments_adjustments(shippings_df)

shippings_df

,ShipmentID,OrderID,ShippedDate,EstimatedDelivery,Carrier,TrackingNumber,OrderDate,Status,DeliveryDate
0,88942,894324,2023-06-29,2023-07-07,UPS,CRw758490960,2021-12-26,Shipped,NaN
1,69419,748520,2022-11-23,2022-12-04,USPS,tNH819055305,2022-06-27,Shipped,NaN
2,47146,757095,2023-07-29,2023-08-04,USPS,lhY270174242,2022-08-25,Shipped,NaN
3,29856,524445,2023-10-17,2023-10-23,FedEx,MPw148874443,2023-08-30,Shipped,NaN
4,11329,132437,2023-08-02,2023-08-10,USPS,yjm151235612,2022-07-04,Shipped,NaN
...,...,...,...,...,...,...,...,...,...
6698,97643,735373,2023-06-09,2023-06-18,USPS,wuE791701527,2022-04-18,Shipped,NaN
6699,56335,978001,2022-07-27,2022-08-01,UPS,MTr644249271,2023-07-13,Shipped,NaN
6700,90373,305589,2023-10-12,2023-10-21,FedEx,KJK047070429,2023-02-18,Shipped,NaN
6701,8526,838615,2023-06-28,2023-07-10,DHL,CiJ950840658,2022-08-06,Shipped,NaN
6702,40658,232569,2023-03-04,2023-03-11,DHL,nQK747558476,2021-12-16,Shipped,NaN

In [6]:
shippings_df

,ShipmentID,OrderID,ShippedDate,EstimatedDelivery,Carrier,TrackingNumber,OrderDate
0,88942,894324,2023-06-29,2023-07-07,UPS,CRw758490960,2021-12-26
1,69419,748520,2022-11-23,2022-12-04,USPS,tNH819055305,2022-06-27
2,47146,757095,2023-07-29,2023-08-04,USPS,lhY270174242,2022-08-25
3,29856,524445,2023-10-17,2023-10-23,FedEx,MPw148874443,2023-08-30
4,11329,132437,2023-08-02,2023-08-10,USPS,yjm151235612,2022-07-04
...,...,...,...,...,...,...,...
6698,97643,735373,2023-06-09,2023-06-18,USPS,wuE791701527,2022-04-18
6699,56335,978001,2022-07-27,2022-08-01,UPS,MTr644249271,2023-07-13
6700,90373,305589,2023-10-12,2023-10-21,FedEx,KJK047070429,2023-02-18
6701,8526,838615,2023-06-28,2023-07-10,DHL,CiJ950840658,2022-08-06
6702,40658,232569,2023-03-04,2023-03-11,DHL,nQK747558476,2021-12-16